from app.models.base import TimestampMixin, UUIDMixin, SoftDeleteMixin
from app.models.company import Company
from app.models.platform import (
    CompanyReportingEventReceipt,
    CompanyReportingFact,
    CompanyReportingSourceState,
    PlatformOperator,
    PlatformOperationsSnapshot,
    PlatformSession,
    PlatformTenantProfile,
    PlatformTenantUsageSnapshot,
    SaasAccountCredential,
    SaasTenantMembership,
)
from app.models.branch import Branch
from app.models.role import Role, Permission, role_permissions_table
from app.models.user import User, UserBranch
from app.models.staff_assignment import StaffRoleAssignment
from app.models.audit import AuditLog
from app.models.auth import RefreshToken
from app.models.approval import ApprovalGrantUsage, ManagerPinCredential
from app.models.device import DeviceRegistration
from app.models.product import (
    Unit,
    Category,
    Product,
    ProductVariant,
    ProductImage,
    PriceList,
    PriceListItem,
)
from app.models.stock import StockLocation, StockBalance, StockMovement
from app.models.shared_kitchen import (
    CompanyIngredient,
    CompanyIngredientAlias,
    CompanyIngredientLot,
    CompanyKitchen,
    CompanyKitchenMovement,
    CompanyProductionDemand,
    CompanyProductionInput,
    CompanyProductionOrder,
)
from app.models.distribution import (
    CompanyDistributionDemand,
    CompanyDistributionEvent,
    CompanyDistributionShipment,
)
from app.models.pos import CashierShift, SaleOrder, SaleOrderItem, Payment
from app.models.purchase import (
    Supplier,
    PurchaseOrder,
    PurchaseOrderItem,
    GoodsReceipt,
    GoodsReceiptItem,
)
from app.models.transfer import TransferOrder, TransferOrderItem
from app.models.stock_count import StockCountSession, StockCountItem
from app.models.settings import BranchSettings, UserInvitation
from app.models.user_access import UserAccessRequest
from app.models.accounting import Account, JournalEntry, JournalLine, AccountBalance
from app.models.integration import OperationalOutboxEvent
from app.models.entitlement import BrandModuleEntitlement
from app.models.saas_billing import SaasBillingEvent, SaasInvoice, SaasPlan, SaasSubscription
from app.models.saas_privacy_support import (
    SaasPrivacyRequest,
    SaasRetentionDecision,
    SaasSupportAccessGrant,
    SaasSupportMessage,
    SaasSupportTicket,
)
from app.models.etax import TaxDocument, TaxDocumentItem
from app.models.tax_settings import BranchTaxProfile, CompanyTaxProfile, TaxRateRule
from app.models.tax_operations import TaxExportBatch, TaxLedgerEntry, TaxPeriod, TaxReconciliationIssue
from app.models.payable import SupplierInvoice, APPayment, APPaymentAllocation, WHTCertificate
from app.models.hr import (
    Department,
    Position,
    Employee,
    SalaryComponent,
    EmployeeSalary,
    PayrollRun,
    PayrollItem,
    PayrollItemLine,
    WorkSchedule,
    PublicHoliday,
    AttendanceRecord,
    LeaveType,
    LeaveBalance,
    LeaveRequest,
)
from app.models.crm import (
    CustomerTier,
    Customer,
    LoyaltySettings,
    PointsTransaction,
    CustomerTag,
    CustomerTagAssignment,
)
from app.models.api_integration import APIKey, WebhookEndpoint, WebhookDelivery, ExternalOrder
from app.models.logistics import Carrier, ShippingRate, Shipment, ShipmentItem, ShipmentEvent
from app.models.payment_gateway import PaymentGatewayConfig, PaymentSession, NotificationLog
from app.models.restaurant import (
    Brand, BrandBranch,
    BranchReplenishmentPolicy,
    Recipe, RecipeIngredient,
    DiningTable, DiningSession, DiningOrder, DiningOrderItem, KitchenTicket,
    WapShiftClosure, WapShiftClosureItem, CentralOrder, CentralOrderItem, CentralOrderShiftClosure,
    CreditAccount, CreditLedger,
    ProductionBatch, ProductionBatchLine,
    StockCutoverRun, StockCutoverItem,
)
from app.models.takeaway import (
    TakeawayBranchCatalogItem,
    TakeawayCatalogItem,
    TakeawayCategory,
    TakeawayCentralOrder,
    TakeawayCentralOrderItem,
    TakeawayCentralOrderRound,
    TakeawayCreditAccount,
    TakeawayCreditEntry,
    TakeawayCreditPaymentConfig,
    TakeawayCreditTopupRequest,
    TakeawayCutoverRun,
    TakeawayHistoricalArchive,
    TakeawayImportBatch,
    TakeawayImportRecord,
    TakeawayKitchenTicket,
    TakeawayOperationalOutbox,
    TakeawayOrder,
    TakeawayOrderItem,
    TakeawayPayment,
    TakeawayPickupToken,
    TakeawayProductionBatch,
    TakeawayProductionLine,
    TakeawayRecipe,
    TakeawayRecipeIngredient,
    TakeawayReceipt,
    TakeawayReferenceProjection,
    TakeawayShift,
    TakeawayStockLocation,
    TakeawayStockBalance,
    TakeawayStockMovement,
    TakeawayTransfer,
    TakeawayTransferItem,
    TakeawayUnit,
    TakeawayReplenishmentPolicy,
)

__all__ = [
    "TimestampMixin",
    "UUIDMixin",
    "SoftDeleteMixin",
    "Company",
    "CompanyReportingEventReceipt",
    "CompanyReportingFact",
    "CompanyReportingSourceState",
    "PlatformOperator",
    "PlatformOperationsSnapshot",
    "PlatformTenantProfile",
    "PlatformTenantUsageSnapshot",
    "SaasAccountCredential",
    "SaasTenantMembership",
    "SaasBillingEvent",
    "SaasInvoice",
    "SaasPlan",
    "SaasSubscription",
    "SaasPrivacyRequest",
    "SaasRetentionDecision",
    "SaasSupportTicket",
    "SaasSupportMessage",
    "SaasSupportAccessGrant",
    "Branch",
    "Role",
    "Permission",
    "role_permissions_table",
    "User",
    "UserBranch",
    "StaffRoleAssignment",
    "AuditLog",
    "RefreshToken",
    "ManagerPinCredential",
    "ApprovalGrantUsage",
    "DeviceRegistration",
    "Unit",
    "Category",
    "Product",
    "ProductVariant",
    "ProductImage",
    "PriceList",
    "PriceListItem",
    "StockLocation",
    "StockBalance",
    "StockMovement",
    "CompanyKitchen",
    "CompanyIngredient",
    "CompanyIngredientAlias",
    "CompanyIngredientLot",
    "CompanyKitchenMovement",
    "CompanyProductionDemand",
    "CompanyProductionOrder",
    "CompanyProductionInput",
    "CompanyDistributionDemand",
    "CompanyDistributionShipment",
    "CompanyDistributionEvent",
    "CashierShift",
    "SaleOrder",
    "SaleOrderItem",
    "Payment",
    "Supplier",
    "PurchaseOrder",
    "PurchaseOrderItem",
    "GoodsReceipt",
    "GoodsReceiptItem",
    "TransferOrder",
    "TransferOrderItem",
    "StockCountSession",
    "StockCountItem",
    "BranchSettings",
    "UserInvitation",
    "UserAccessRequest",
    "Account",
    "JournalEntry",
    "JournalLine",
    "AccountBalance",
    "TaxDocument",
    "TaxDocumentItem",
    "CompanyTaxProfile",
    "BranchTaxProfile",
    "TaxRateRule",
    "TaxLedgerEntry",
    "TaxPeriod",
    "TaxReconciliationIssue",
    "TaxExportBatch",
    "SupplierInvoice",
    "APPayment",
    "APPaymentAllocation",
    "WHTCertificate",
    "Department",
    "Position",
    "Employee",
    "SalaryComponent",
    "EmployeeSalary",
    "PayrollRun",
    "PayrollItem",
    "PayrollItemLine",
    "WorkSchedule",
    "PublicHoliday",
    "AttendanceRecord",
    "LeaveType",
    "LeaveBalance",
    "LeaveRequest",
    "CustomerTier",
    "Customer",
    "LoyaltySettings",
    "PointsTransaction",
    "CustomerTag",
    "CustomerTagAssignment",
    "APIKey",
    "WebhookEndpoint",
    "WebhookDelivery",
    "ExternalOrder",
    "Carrier",
    "ShippingRate",
    "Shipment",
    "ShipmentItem",
    "ShipmentEvent",
    "PaymentGatewayConfig",
    "PaymentSession",
    "NotificationLog",
    "Brand",
    "BrandBranch",
    "BranchReplenishmentPolicy",
    "Recipe",
    "RecipeIngredient",
    "DiningTable",
    "DiningSession",
    "DiningOrder",
    "DiningOrderItem",
    "KitchenTicket",
    "WapShiftClosure",
    "WapShiftClosureItem",
    "CentralOrder",
    "CentralOrderItem",
    "CentralOrderShiftClosure",
    "CreditAccount",
    "CreditLedger",
    "ProductionBatch",
    "ProductionBatchLine",
    "StockCutoverRun",
    "StockCutoverItem",
    "TakeawayBranchCatalogItem",
    "TakeawayCatalogItem",
    "TakeawayCategory",
    "TakeawayCentralOrder",
    "TakeawayCentralOrderItem",
    "TakeawayCentralOrderRound",
    "TakeawayCreditAccount",
    "TakeawayCreditEntry",
    "TakeawayCreditPaymentConfig",
    "TakeawayCreditTopupRequest",
    "TakeawayCutoverRun",
    "TakeawayHistoricalArchive",
    "TakeawayImportBatch",
    "TakeawayImportRecord",
    "TakeawayKitchenTicket",
    "TakeawayOperationalOutbox",
    "TakeawayOrder",
    "TakeawayOrderItem",
    "TakeawayPayment",
    "TakeawayPickupToken",
    "TakeawayProductionBatch",
    "TakeawayProductionLine",
    "TakeawayRecipe",
    "TakeawayRecipeIngredient",
    "TakeawayReceipt",
    "TakeawayReferenceProjection",
    "TakeawayShift",
    "TakeawayStockLocation",
    "TakeawayStockBalance",
    "TakeawayStockMovement",
    "TakeawayTransfer",
    "TakeawayTransferItem",
    "TakeawayUnit",
    "TakeawayReplenishmentPolicy",
]
