"""add_payment_gateway_and_notifications

Revision ID: 1440f535ece8
Revises: 859c31748f25
Create Date: 2026-05-15 15:43:20.668850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1440f535ece8'
down_revision: Union[str, None] = '859c31748f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'notification_logs',
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('channel', sa.String(length=20), nullable=False),
        sa.Column('recipient', sa.String(length=255), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('subject', sa.String(length=255), nullable=True),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=20), server_default=sa.text("'sent'"), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('reference_type', sa.String(length=50), nullable=True),
        sa.Column('reference_id', sa.String(length=100), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_notification_logs_company_id_companies')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs')),
    )
    op.create_index(op.f('ix_notification_logs_company_id'), 'notification_logs', ['company_id'], unique=False)
    op.create_table(
        'payment_gateway_configs',
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('omise_public_key', sa.String(length=255), nullable=True),
        sa.Column('omise_secret_key', sa.String(length=500), nullable=True),
        sa.Column('omise_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('twoc2p_merchant_id', sa.String(length=100), nullable=True),
        sa.Column('twoc2p_secret_key', sa.String(length=500), nullable=True),
        sa.Column('twoc2p_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('promptpay_target', sa.String(length=20), nullable=True),
        sa.Column('promptpay_name', sa.String(length=255), nullable=True),
        sa.Column('promptpay_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('scb_api_key', sa.String(length=500), nullable=True),
        sa.Column('scb_api_secret', sa.String(length=500), nullable=True),
        sa.Column('scb_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('line_notify_token', sa.String(length=500), nullable=True),
        sa.Column('line_notify_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('smtp_host', sa.String(length=255), nullable=True),
        sa.Column('smtp_port', sa.Integer(), server_default=sa.text('587'), nullable=False),
        sa.Column('smtp_username', sa.String(length=255), nullable=True),
        sa.Column('smtp_password', sa.String(length=500), nullable=True),
        sa.Column('smtp_from_email', sa.String(length=255), nullable=True),
        sa.Column('smtp_from_name', sa.String(length=255), nullable=True),
        sa.Column('smtp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payment_gateway_configs_company_id_companies')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_gateway_configs')),
        sa.UniqueConstraint('company_id', name=op.f('uq_payment_gateway_configs_company_id')),
    )
    op.create_table(
        'payment_sessions',
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('branch_id', sa.UUID(), nullable=False),
        sa.Column('session_ref', sa.String(length=100), nullable=False),
        sa.Column('gateway', sa.String(length=20), nullable=False),
        sa.Column('method', sa.String(length=30), nullable=False),
        sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), server_default=sa.text("'THB'"), nullable=False),
        sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
        sa.Column('reference_type', sa.String(length=50), nullable=True),
        sa.Column('reference_id', sa.String(length=100), nullable=True),
        sa.Column('gateway_ref', sa.String(length=255), nullable=True),
        sa.Column('gateway_status', sa.String(length=50), nullable=True),
        sa.Column('gateway_payload', sa.JSON(), nullable=True),
        sa.Column('qr_payload', sa.Text(), nullable=True),
        sa.Column('redirect_url', sa.String(length=500), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_payment_sessions_branch_id_branches')),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payment_sessions_company_id_companies')),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payment_sessions_created_by_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_sessions')),
        sa.UniqueConstraint('session_ref', name=op.f('uq_payment_sessions_session_ref')),
    )
    op.create_index(op.f('ix_payment_sessions_branch_id'), 'payment_sessions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_payment_sessions_company_id'), 'payment_sessions', ['company_id'], unique=False)
    op.create_index('ix_payment_sessions_company_id_session_ref', 'payment_sessions', ['company_id', 'session_ref'], unique=False)
    op.create_index('ix_payment_sessions_gateway_ref', 'payment_sessions', ['gateway_ref'], unique=False)
    op.create_index('ix_payment_sessions_status', 'payment_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_sessions_status', table_name='payment_sessions')
    op.drop_index('ix_payment_sessions_gateway_ref', table_name='payment_sessions')
    op.drop_index('ix_payment_sessions_company_id_session_ref', table_name='payment_sessions')
    op.drop_index(op.f('ix_payment_sessions_company_id'), table_name='payment_sessions')
    op.drop_index(op.f('ix_payment_sessions_branch_id'), table_name='payment_sessions')
    op.drop_table('payment_sessions')
    op.drop_table('payment_gateway_configs')
    op.drop_index(op.f('ix_notification_logs_company_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###
