"""add_crm_and_loyalty

Revision ID: 4bb56123b795
Revises: 5ffa58478203
Create Date: 2026-05-15 02:42:36.965247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4bb56123b795'
down_revision: Union[str, None] = '5ffa58478203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_tags',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), server_default=sa.text("'#6366f1'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_tags_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_tags')),
    sa.UniqueConstraint('company_id', 'name', name='uq_customer_tags_company_id_name')
    )
    op.create_index(op.f('ix_customer_tags_company_id'), 'customer_tags', ['company_id'], unique=False)
    op.create_table('customer_tiers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_th', sa.String(length=100), nullable=False),
    sa.Column('min_lifetime_spend', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('points_multiplier', sa.Numeric(precision=4, scale=2), server_default=sa.text('1.0'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customer_tiers_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_tiers')),
    sa.UniqueConstraint('company_id', 'name', name='uq_customer_tiers_company_id_name')
    )
    op.create_index(op.f('ix_customer_tiers_company_id'), 'customer_tiers', ['company_id'], unique=False)
    op.create_table('loyalty_settings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('earn_rate', sa.Numeric(precision=10, scale=4), server_default=sa.text('1.0'), nullable=False),
    sa.Column('earn_min_spend', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('redeem_rate', sa.Numeric(precision=10, scale=4), server_default=sa.text('0.1'), nullable=False),
    sa.Column('redeem_min_points', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('redeem_max_pct', sa.Numeric(precision=5, scale=2), server_default=sa.text('100'), nullable=False),
    sa.Column('points_expiry_months', sa.Integer(), server_default=sa.text('12'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('require_phone', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_loyalty_settings_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loyalty_settings')),
    sa.UniqueConstraint('company_id', name=op.f('uq_loyalty_settings_company_id'))
    )
    op.create_table('customers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=True),
    sa.Column('customer_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('points_balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lifetime_spend', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('lifetime_points_earned', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lifetime_points_redeemed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_orders', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_purchase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_customers_company_id_companies')),
    sa.ForeignKeyConstraint(['tier_id'], ['customer_tiers.id'], name=op.f('fk_customers_tier_id_customer_tiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('company_id', 'customer_code', name='uq_customers_company_id_customer_code')
    )
    op.create_index('ix_customers_company_email', 'customers', ['company_id', 'email'], unique=False)
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_index('ix_customers_company_phone', 'customers', ['company_id', 'phone'], unique=False)
    op.create_index('ix_customers_company_phone_unique', 'customers', ['company_id', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_tier_id'), 'customers', ['tier_id'], unique=False)
    op.create_table('customer_tag_assignments',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_tag_assignments_customer_id_customers')),
    sa.ForeignKeyConstraint(['tag_id'], ['customer_tags.id'], name=op.f('fk_customer_tag_assignments_tag_id_customer_tags')),
    sa.PrimaryKeyConstraint('customer_id', 'tag_id', name='pk_customer_tag_assignments')
    )
    op.create_table('points_transactions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('spend_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('redeem_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_points_transactions_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_points_transactions_created_by_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_points_transactions_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_points_transactions'))
    )
    op.create_index(op.f('ix_points_transactions_company_id'), 'points_transactions', ['company_id'], unique=False)
    op.create_index('ix_points_transactions_company_transaction_type', 'points_transactions', ['company_id', 'transaction_type'], unique=False)
    op.create_index('ix_points_transactions_customer_created_at', 'points_transactions', ['customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_points_transactions_customer_id'), 'points_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_points_transactions_reference_id'), 'points_transactions', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_transactions_reference_id'), table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_customer_id'), table_name='points_transactions')
    op.drop_index('ix_points_transactions_customer_created_at', table_name='points_transactions')
    op.drop_index('ix_points_transactions_company_transaction_type', table_name='points_transactions')
    op.drop_index(op.f('ix_points_transactions_company_id'), table_name='points_transactions')
    op.drop_table('points_transactions')
    op.drop_table('customer_tag_assignments')
    op.drop_index(op.f('ix_customers_tier_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index('ix_customers_company_phone_unique', table_name='customers', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_index('ix_customers_company_phone', table_name='customers')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_index('ix_customers_company_email', table_name='customers')
    op.drop_table('customers')
    op.drop_table('loyalty_settings')
    op.drop_index(op.f('ix_customer_tiers_company_id'), table_name='customer_tiers')
    op.drop_table('customer_tiers')
    op.drop_index(op.f('ix_customer_tags_company_id'), table_name='customer_tags')
    op.drop_table('customer_tags')
    # ### end Alembic commands ###
