"""add_attendance_and_leave

Revision ID: 5ffa58478203
Revises: 7099cf5bc8c4
Create Date: 2026-05-15 02:05:52.518524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '5ffa58478203'
down_revision: Union[str, None] = '7099cf5bc8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('days_per_year', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('carry_over', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('max_carry_over', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('requires_doc', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('gender_restrict', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_types_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_types')),
    sa.UniqueConstraint('company_id', 'code', name='uq_leave_types_company_id_code')
    )
    op.create_index(op.f('ix_leave_types_company_id'), 'leave_types', ['company_id'], unique=False)
    op.create_table('public_holidays',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_public_holidays_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_holidays')),
    sa.UniqueConstraint('company_id', 'holiday_date', name='uq_public_holidays_company_id_holiday_date')
    )
    op.create_index(op.f('ix_public_holidays_company_id'), 'public_holidays', ['company_id'], unique=False)
    op.create_table('work_schedules',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('work_days', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('break_minutes', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_work_schedules_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_schedules'))
    )
    op.create_index(op.f('ix_work_schedules_company_id'), 'work_schedules', ['company_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_minutes', sa.Integer(), nullable=True),
    sa.Column('ot_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ot_rate', sa.Numeric(precision=4, scale=2), server_default=sa.text('1.5'), nullable=False),
    sa.Column('ot_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('is_absent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_late', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('late_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('entry_type', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_attendance_records_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_attendance_records_created_by_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_records_employee_id_employees')),
    sa.ForeignKeyConstraint(['schedule_id'], ['work_schedules.id'], name=op.f('fk_attendance_records_schedule_id_work_schedules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_attendance_records_employee_id_work_date')
    )
    op.create_index(op.f('ix_attendance_records_company_id'), 'attendance_records', ['company_id'], unique=False)
    op.create_index('ix_attendance_records_company_work_date', 'attendance_records', ['company_id', 'work_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index('ix_attendance_records_employee_work_date', 'attendance_records', ['employee_id', 'work_date'], unique=False)
    op.create_table('leave_balances',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entitled_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=5, scale=1), server_default=sa.text('0'), nullable=False),
    sa.Column('remaining_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('carry_over_days', sa.Numeric(precision=5, scale=1), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_balances_company_id_companies')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_balances_employee_id_employees')),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_balances_leave_type_id_leave_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_balances')),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_leave_balances_employee_leave_type_year')
    )
    op.create_index(op.f('ix_leave_balances_company_id'), 'leave_balances', ['company_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_leave_type_id'), 'leave_balances', ['leave_type_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('request_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_requested', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('auto_attendance', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_requests_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_leave_requests_created_by_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_requests_employee_id_employees')),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_requests_leave_type_id_leave_types')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_leave_requests_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests')),
    sa.UniqueConstraint('request_number', name=op.f('uq_leave_requests_request_number'))
    )
    op.create_index(op.f('ix_leave_requests_company_id'), 'leave_requests', ['company_id'], unique=False)
    op.create_index('ix_leave_requests_company_request_number', 'leave_requests', ['company_id', 'request_number'], unique=False)
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index('ix_leave_requests_employee_start_date', 'leave_requests', ['employee_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_leave_type_id'), 'leave_requests', ['leave_type_id'], unique=False)
    op.create_index('ix_leave_requests_status', 'leave_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leave_requests_status', table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_leave_type_id'), table_name='leave_requests')
    op.drop_index('ix_leave_requests_employee_start_date', table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_index('ix_leave_requests_company_request_number', table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_company_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_leave_balances_leave_type_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_company_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index('ix_attendance_records_employee_work_date', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index('ix_attendance_records_company_work_date', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_company_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_work_schedules_company_id'), table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index(op.f('ix_public_holidays_company_id'), table_name='public_holidays')
    op.drop_table('public_holidays')
    op.drop_index(op.f('ix_leave_types_company_id'), table_name='leave_types')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
