"""create retail operational schema

Revision ID: p8retail0002
Revises: p7retail0001
Create Date: 2026-09-15 02:13:01.096274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'p8retail0002'
down_revision: Union[str, None] = 'p7retail0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_grant_usages',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('grant_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("action IN ('pos.discount.override', 'pos.sale.void', 'pos.refund.create', 'inventory.stock.adjust')", name=op.f('ck_approval_grant_usages_supported_action')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_grant_usages')),
    sa.UniqueConstraint('grant_id', name='uq_approval_grant_usages_grant_id')
    )
    op.create_index('ix_approval_grant_usages_company_branch_consumed', 'approval_grant_usages', ['company_id', 'branch_id', 'consumed_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_branch_id'), 'audit_logs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_slug', sa.String(length=63), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('vat_registered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('address_en', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'THB'"), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'Asia/Bangkok'"), nullable=False),
    sa.Column('fiscal_year_start', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('credential_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credential_version > 0', name=op.f('ck_companies_company_credential_version_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index(op.f('ix_companies_business_slug'), 'companies', ['business_slug'], unique=True)
    op.create_table('operational_outbox_events',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('contract_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_outbox_events')),
    sa.UniqueConstraint('idempotency_key', name='uq_operational_outbox_events_idempotency_key')
    )
    op.create_index(op.f('ix_operational_outbox_events_aggregate_id'), 'operational_outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_operational_outbox_events_branch_id'), 'operational_outbox_events', ['branch_id'], unique=False)
    op.create_index(op.f('ix_operational_outbox_events_brand_id'), 'operational_outbox_events', ['brand_id'], unique=False)
    op.create_index(op.f('ix_operational_outbox_events_company_id'), 'operational_outbox_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_operational_outbox_events_created_at'), 'operational_outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_operational_outbox_events_event_type'), 'operational_outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_operational_outbox_events_status'), 'operational_outbox_events', ['status'], unique=False)
    op.create_table('branches',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('google_maps_url', sa.String(length=500), nullable=True),
    sa.Column('is_warehouse', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branches_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('company_id', 'code', name='uq_branches_company_id_code')
    )
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_table('categories',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_categories_company_id_companies')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('ix_categories_company_code_not_null_unique', 'categories', ['company_id', 'code'], unique=True, postgresql_where=sa.text('code IS NOT NULL'))
    op.create_index(op.f('ix_categories_company_id'), 'categories', ['company_id'], unique=False)
    op.create_table('price_lists',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'THB'"), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_price_lists_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_lists'))
    )
    op.create_index(op.f('ix_price_lists_company_id'), 'price_lists', ['company_id'], unique=False)
    op.create_table('units',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('decimal_places', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_units_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units')),
    sa.UniqueConstraint('company_id', 'code', name='uq_units_company_id_code')
    )
    op.create_index(op.f('ix_units_company_id'), 'units', ['company_id'], unique=False)
    op.create_table('users',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('company_id', 'username', name='uq_users_company_id_username')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index('ix_users_company_id_email_unique', 'users', ['company_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('branch_settings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('pos_receipt_header', sa.Text(), nullable=True),
    sa.Column('pos_receipt_footer', sa.Text(), nullable=True),
    sa.Column('pos_require_customer', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pos_allow_discount', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('pos_max_discount_pct', sa.Numeric(precision=5, scale=2), server_default=sa.text('100'), nullable=False),
    sa.Column('pos_cashier_discount_limit_pct', sa.Numeric(precision=5, scale=2), server_default=sa.text('10'), nullable=False),
    sa.Column('stock_adjust_approval_threshold_qty', sa.Numeric(precision=12, scale=4), server_default=sa.text('10'), nullable=False),
    sa.Column('pos_default_price_list_id', sa.UUID(), nullable=True),
    sa.Column('promptpay_target', sa.String(length=20), nullable=True),
    sa.Column('promptpay_name', sa.String(length=255), nullable=True),
    sa.Column('promptpay_qr_url', sa.String(length=500), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('public_storefront_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allow_negative_stock', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('low_stock_alert_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('receipt_show_tax_id', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('receipt_show_logo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('receipt_logo_url', sa.String(length=500), nullable=True),
    sa.Column('receipt_copies', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('notify_low_stock_email', sa.String(length=255), nullable=True),
    sa.Column('fb_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fb_service_mode', sa.String(length=20), server_default=sa.text("'quick_service'"), nullable=False),
    sa.Column('fb_table_qr_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fb_bill_at_table', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fb_queue_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fb_queue_reset', sa.String(length=20), server_default=sa.text("'daily'"), nullable=False),
    sa.Column('fb_queue_prefix', sa.String(length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('fb_pickup_display_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fb_line_notify_token', sa.String(length=255), nullable=True),
    sa.Column('fb_line_mode', sa.String(length=20), server_default=sa.text("'group'"), nullable=False),
    sa.Column('fb_kitchen_stations', sa.JSON(), nullable=True),
    sa.Column('fb_setup_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fb_qs_qr_token', sa.UUID(), nullable=True, comment='QR token สำหรับ Quick Service (shop-level)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pos_cashier_discount_limit_pct >= 0 AND pos_cashier_discount_limit_pct <= pos_max_discount_pct', name=op.f('ck_branch_settings_pos_cashier_discount_limit_within_max')),
    sa.CheckConstraint('pos_max_discount_pct >= 0 AND pos_max_discount_pct <= 100', name=op.f('ck_branch_settings_pos_max_discount_range')),
    sa.CheckConstraint('stock_adjust_approval_threshold_qty >= 0', name=op.f('ck_branch_settings_stock_adjust_approval_threshold_nonnegative')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_branch_settings_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_branch_settings_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_settings')),
    sa.UniqueConstraint('branch_id', name=op.f('uq_branch_settings_branch_id')),
    sa.UniqueConstraint('fb_qs_qr_token', name=op.f('uq_branch_settings_fb_qs_qr_token'))
    )
    op.create_index(op.f('ix_branch_settings_company_id'), 'branch_settings', ['company_id'], unique=False)
    op.create_table('stock_locations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_locations_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_locations_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_locations')),
    sa.UniqueConstraint('branch_id', 'code', name='uq_stock_locations_branch_id_code')
    )
    op.create_index(op.f('ix_stock_locations_branch_id'), 'stock_locations', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_locations_company_id'), 'stock_locations', ['company_id'], unique=False)
    op.create_table('brands',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('central_branch_id', sa.UUID(), nullable=True),
    sa.Column('central_location_id', sa.UUID(), nullable=True),
    sa.Column('central_ready_location_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=30), server_default=sa.text("'restaurant'"), nullable=False),
    sa.Column('storefront_mode', sa.String(length=50), server_default=sa.text("'food_stall'"), nullable=False),
    sa.Column('theme_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("business_type IN ('restaurant', 'retail_pos', 'takeaway')", name=op.f('ck_brands_ck_brands_business_type')),
    sa.ForeignKeyConstraint(['central_branch_id'], ['branches.id'], name=op.f('fk_brands_central_branch_id_branches')),
    sa.ForeignKeyConstraint(['central_location_id'], ['stock_locations.id'], name=op.f('fk_brands_central_location_id_stock_locations')),
    sa.ForeignKeyConstraint(['central_ready_location_id'], ['stock_locations.id'], name=op.f('fk_brands_central_ready_location_id_stock_locations')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_brands_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('company_id', 'slug', name='uq_brands_company_slug')
    )
    op.create_index(op.f('ix_brands_business_type'), 'brands', ['business_type'], unique=False)
    op.create_index(op.f('ix_brands_central_branch_id'), 'brands', ['central_branch_id'], unique=False)
    op.create_index(op.f('ix_brands_central_location_id'), 'brands', ['central_location_id'], unique=False)
    op.create_index(op.f('ix_brands_central_ready_location_id'), 'brands', ['central_ready_location_id'], unique=False)
    op.create_index('ix_brands_company_active', 'brands', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_brands_company_id'), 'brands', ['company_id'], unique=False)
    op.create_table('cashier_shifts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shift_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_cash', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('closing_cash', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_difference', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_orders', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_voids', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_cashier_shifts_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_cashier_shifts_company_id_companies')),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_cashier_shifts_location_id_stock_locations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cashier_shifts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cashier_shifts'))
    )
    op.create_index(op.f('ix_cashier_shifts_branch_id'), 'cashier_shifts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cashier_shifts_company_id'), 'cashier_shifts', ['company_id'], unique=False)
    op.create_index(op.f('ix_cashier_shifts_location_id'), 'cashier_shifts', ['location_id'], unique=False)
    op.create_index('ix_cashier_shifts_user_branch_open_unique', 'cashier_shifts', ['user_id', 'branch_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_index(op.f('ix_cashier_shifts_user_id'), 'cashier_shifts', ['user_id'], unique=False)
    op.create_table('stock_count_sessions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('session_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('count_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('total_items', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_matched', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_over', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('items_short', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_variance_value', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_count_sessions_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_count_sessions_company_id_companies')),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_stock_count_sessions_completed_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_count_sessions_created_by_users')),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_stock_count_sessions_location_id_stock_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_count_sessions')),
    sa.UniqueConstraint('session_number', name=op.f('uq_stock_count_sessions_session_number'))
    )
    op.create_index(op.f('ix_stock_count_sessions_branch_id'), 'stock_count_sessions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_count_sessions_company_id'), 'stock_count_sessions', ['company_id'], unique=False)
    op.create_index('ix_stock_count_sessions_company_id_session_number', 'stock_count_sessions', ['company_id', 'session_number'], unique=False)
    op.create_index(op.f('ix_stock_count_sessions_location_id'), 'stock_count_sessions', ['location_id'], unique=False)
    op.create_index('ix_stock_count_sessions_status', 'stock_count_sessions', ['status'], unique=False)
    op.create_table('brand_branches',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('store_location_id', sa.UUID(), nullable=True),
    sa.Column('branch_type', sa.String(length=30), server_default=sa.text("'company_owned'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_brand_branches_branch_id_branches')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_branches_brand_id_brands'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_brand_branches_company_id_companies')),
    sa.ForeignKeyConstraint(['store_location_id'], ['stock_locations.id'], name=op.f('fk_brand_branches_store_location_id_stock_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_branches')),
    sa.UniqueConstraint('brand_id', 'branch_id', name='uq_brand_branches_brand_branch')
    )
    op.create_index(op.f('ix_brand_branches_branch_id'), 'brand_branches', ['branch_id'], unique=False)
    op.create_index(op.f('ix_brand_branches_brand_id'), 'brand_branches', ['brand_id'], unique=False)
    op.create_index('ix_brand_branches_company_brand', 'brand_branches', ['company_id', 'brand_id'], unique=False)
    op.create_index(op.f('ix_brand_branches_company_id'), 'brand_branches', ['company_id'], unique=False)
    op.create_index(op.f('ix_brand_branches_store_location_id'), 'brand_branches', ['store_location_id'], unique=False)
    op.create_index('uq_brand_branches_active_branch', 'brand_branches', ['branch_id'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('products',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('name_en', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(length=20), server_default=sa.text("'simple'"), nullable=False),
    sa.Column('inventory_role', sa.String(length=30), nullable=True, comment='central_raw, central_ready, store_local, or not_stocked'),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('vat_type', sa.String(length=20), server_default=sa.text("'included'"), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('7.00'), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_for_sale', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_for_purchase', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('min_stock_qty', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_products_company_id_companies')),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_products_unit_id_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('company_id', 'sku', name='uq_products_company_id_sku')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_inventory_role'), 'products', ['inventory_role'], unique=False)
    op.create_index(op.f('ix_products_unit_id'), 'products', ['unit_id'], unique=False)
    op.create_table('sale_orders',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'completed'"), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_tax_id', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_type', sa.String(length=10), server_default=sa.text("'amount'"), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('7.00'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('change_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_offline', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('client_order_id', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipe_stock_status', sa.String(length=30), nullable=True),
    sa.Column('recipe_stock_warnings', sa.Text(), nullable=True),
    sa.Column('recipe_stock_posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipe_stock_reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_sale_orders_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sale_orders_company_id_companies')),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_sale_orders_location_id_stock_locations')),
    sa.ForeignKeyConstraint(['shift_id'], ['cashier_shifts.id'], name=op.f('fk_sale_orders_shift_id_cashier_shifts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sale_orders_user_id_users')),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], name=op.f('fk_sale_orders_voided_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_orders')),
    sa.UniqueConstraint('company_id', 'client_order_id', name='uq_sale_orders_client_order_id'),
    sa.UniqueConstraint('order_number', name=op.f('uq_sale_orders_order_number'))
    )
    op.create_index(op.f('ix_sale_orders_branch_id'), 'sale_orders', ['branch_id'], unique=False)
    op.create_index(op.f('ix_sale_orders_company_id'), 'sale_orders', ['company_id'], unique=False)
    op.create_index('ix_sale_orders_company_id_order_number', 'sale_orders', ['company_id', 'order_number'], unique=False)
    op.create_index('ix_sale_orders_created_at', 'sale_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_sale_orders_location_id'), 'sale_orders', ['location_id'], unique=False)
    op.create_index(op.f('ix_sale_orders_shift_id'), 'sale_orders', ['shift_id'], unique=False)
    op.create_index('ix_sale_orders_status', 'sale_orders', ['status'], unique=False)
    op.create_index(op.f('ix_sale_orders_user_id'), 'sale_orders', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('original_payment_id', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_payments_company_id_companies')),
    sa.ForeignKeyConstraint(['order_id'], ['sale_orders.id'], name=op.f('fk_payments_order_id_sale_orders')),
    sa.ForeignKeyConstraint(['original_payment_id'], ['payments.id'], name=op.f('fk_payments_original_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_original_payment_id'), 'payments', ['original_payment_id'], unique=False)
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_images_company_id_companies')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images'))
    )
    op.create_index(op.f('ix_product_images_company_id'), 'product_images', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_product_variants_company_id_companies')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('company_id', 'sku', name='uq_product_variants_company_id_sku')
    )
    op.create_index(op.f('ix_product_variants_barcode'), 'product_variants', ['barcode'], unique=False)
    op.create_index(op.f('ix_product_variants_company_id'), 'product_variants', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('price_list_items',
    sa.Column('price_list_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=15, scale=4), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_price_list_items_company_id_companies')),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], name=op.f('fk_price_list_items_price_list_id_price_lists')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_list_items_product_id_products')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_price_list_items_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_list_items')),
    sa.UniqueConstraint('price_list_id', 'product_id', 'variant_id', name='uq_price_list_items_price_list_product_variant')
    )
    op.create_index(op.f('ix_price_list_items_company_id'), 'price_list_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_price_list_id'), 'price_list_items', ['price_list_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_product_id'), 'price_list_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_variant_id'), 'price_list_items', ['variant_id'], unique=False)
    op.create_table('sale_order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('variant_name', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('unit_code', sa.String(length=20), nullable=True),
    sa.Column('qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_type', sa.String(length=10), server_default=sa.text("'amount'"), nullable=False),
    sa.Column('vat_type', sa.String(length=20), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('7.00'), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('refunded_qty', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sale_order_items_company_id_companies')),
    sa.ForeignKeyConstraint(['order_id'], ['sale_orders.id'], name=op.f('fk_sale_order_items_order_id_sale_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sale_order_items_product_id_products')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_sale_order_items_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_order_items'))
    )
    op.create_index(op.f('ix_sale_order_items_company_id'), 'sale_order_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_sale_order_items_order_id'), 'sale_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_sale_order_items_product_id'), 'sale_order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_order_items_variant_id'), 'sale_order_items', ['variant_id'], unique=False)
    op.create_table('stock_balances',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('qty_on_hand', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('qty_reserved', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('last_movement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_balances_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_balances_company_id_companies')),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_stock_balances_location_id_stock_locations')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_balances_product_id_products')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_stock_balances_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_balances')),
    sa.UniqueConstraint('location_id', 'product_id', 'variant_id', name='uq_stock_balances_location_product_variant')
    )
    op.create_index(op.f('ix_stock_balances_branch_id'), 'stock_balances', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_company_id'), 'stock_balances', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_location_id'), 'stock_balances', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_product_id'), 'stock_balances', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_variant_id'), 'stock_balances', ['variant_id'], unique=False)
    op.create_table('stock_count_items',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('unit_code', sa.String(length=20), nullable=True),
    sa.Column('expected_qty', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('variance_qty', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('variance_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('counted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counted_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('is_adjusted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_count_items_company_id_companies')),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], name=op.f('fk_stock_count_items_counted_by_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_count_items_product_id_products')),
    sa.ForeignKeyConstraint(['session_id'], ['stock_count_sessions.id'], name=op.f('fk_stock_count_items_session_id_stock_count_sessions')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_stock_count_items_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_count_items')),
    sa.UniqueConstraint('session_id', 'product_id', 'variant_id', name='uq_stock_count_items_session_product_variant')
    )
    op.create_index(op.f('ix_stock_count_items_company_id'), 'stock_count_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_count_items_product_id'), 'stock_count_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_count_items_session_id'), 'stock_count_items', ['session_id'], unique=False)
    op.create_index(op.f('ix_stock_count_items_variant_id'), 'stock_count_items', ['variant_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('qty_before', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('qty_after', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_movements_branch_id_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_stock_movements_company_id_companies')),
    sa.ForeignKeyConstraint(['location_id'], ['stock_locations.id'], name=op.f('fk_stock_movements_location_id_stock_locations')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stock_movements_user_id_users')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_stock_movements_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index(op.f('ix_stock_movements_branch_id'), 'stock_movements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_company_id'), 'stock_movements', ['company_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_location_id'), 'stock_movements', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_user_id'), 'stock_movements', ['user_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_variant_id'), 'stock_movements', ['variant_id'], unique=False)
    op.create_table(
        'retail_reference_projection_receipts',
        sa.Column('aggregate_type', sa.String(length=40), nullable=False),
        sa.Column('aggregate_id', sa.UUID(), nullable=False),
        sa.Column('company_id', sa.UUID(), nullable=True),
        sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('source_digest', sa.String(length=64), nullable=False),
        sa.Column('projected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_retail_reference_projection_receipts')),
        sa.UniqueConstraint(
            'aggregate_type',
            'aggregate_id',
            name='uq_retail_reference_projection_receipt_aggregate',
        ),
    )
    op.create_index(
        'ix_retail_reference_projection_receipts_company',
        'retail_reference_projection_receipts',
        ['company_id', 'aggregate_type'],
        unique=False,
    )
    op.create_table(
        'retail_migration_runs',
        sa.Column('company_id', sa.UUID(), nullable=True),
        sa.Column('selected_brand_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('selected_branch_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('source_database', sa.String(length=100), nullable=False),
        sa.Column('target_database', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('table_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('table_digests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('last_error', sa.String(length=255), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')",
            name=op.f('ck_retail_migration_runs_status'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_retail_migration_runs')),
    )
    op.create_index(
        'ix_retail_migration_runs_company_started',
        'retail_migration_runs',
        ['company_id', 'started_at'],
        unique=False,
    )
    op.execute(
        "UPDATE database_boundary_metadata SET schema_contract_version = 2 "
        "WHERE boundary_name = 'retail'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE database_boundary_metadata SET schema_contract_version = 1 "
        "WHERE boundary_name = 'retail'"
    )
    op.drop_index(
        'ix_retail_migration_runs_company_started',
        table_name='retail_migration_runs',
    )
    op.drop_table('retail_migration_runs')
    op.drop_index(
        'ix_retail_reference_projection_receipts_company',
        table_name='retail_reference_projection_receipts',
    )
    op.drop_table('retail_reference_projection_receipts')
    op.drop_index(op.f('ix_stock_movements_variant_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_user_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_location_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_company_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_branch_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_stock_count_items_variant_id'), table_name='stock_count_items')
    op.drop_index(op.f('ix_stock_count_items_session_id'), table_name='stock_count_items')
    op.drop_index(op.f('ix_stock_count_items_product_id'), table_name='stock_count_items')
    op.drop_index(op.f('ix_stock_count_items_company_id'), table_name='stock_count_items')
    op.drop_table('stock_count_items')
    op.drop_index(op.f('ix_stock_balances_variant_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_product_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_location_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_company_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_branch_id'), table_name='stock_balances')
    op.drop_table('stock_balances')
    op.drop_index(op.f('ix_sale_order_items_variant_id'), table_name='sale_order_items')
    op.drop_index(op.f('ix_sale_order_items_product_id'), table_name='sale_order_items')
    op.drop_index(op.f('ix_sale_order_items_order_id'), table_name='sale_order_items')
    op.drop_index(op.f('ix_sale_order_items_company_id'), table_name='sale_order_items')
    op.drop_table('sale_order_items')
    op.drop_index(op.f('ix_price_list_items_variant_id'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_product_id'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_price_list_id'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_company_id'), table_name='price_list_items')
    op.drop_table('price_list_items')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_company_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_barcode'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_company_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_payments_original_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_sale_orders_user_id'), table_name='sale_orders')
    op.drop_index('ix_sale_orders_status', table_name='sale_orders')
    op.drop_index(op.f('ix_sale_orders_shift_id'), table_name='sale_orders')
    op.drop_index(op.f('ix_sale_orders_location_id'), table_name='sale_orders')
    op.drop_index('ix_sale_orders_created_at', table_name='sale_orders')
    op.drop_index('ix_sale_orders_company_id_order_number', table_name='sale_orders')
    op.drop_index(op.f('ix_sale_orders_company_id'), table_name='sale_orders')
    op.drop_index(op.f('ix_sale_orders_branch_id'), table_name='sale_orders')
    op.drop_table('sale_orders')
    op.drop_index(op.f('ix_products_unit_id'), table_name='products')
    op.drop_index(op.f('ix_products_inventory_role'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index('uq_brand_branches_active_branch', table_name='brand_branches', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_brand_branches_store_location_id'), table_name='brand_branches')
    op.drop_index(op.f('ix_brand_branches_company_id'), table_name='brand_branches')
    op.drop_index('ix_brand_branches_company_brand', table_name='brand_branches')
    op.drop_index(op.f('ix_brand_branches_brand_id'), table_name='brand_branches')
    op.drop_index(op.f('ix_brand_branches_branch_id'), table_name='brand_branches')
    op.drop_table('brand_branches')
    op.drop_index('ix_stock_count_sessions_status', table_name='stock_count_sessions')
    op.drop_index(op.f('ix_stock_count_sessions_location_id'), table_name='stock_count_sessions')
    op.drop_index('ix_stock_count_sessions_company_id_session_number', table_name='stock_count_sessions')
    op.drop_index(op.f('ix_stock_count_sessions_company_id'), table_name='stock_count_sessions')
    op.drop_index(op.f('ix_stock_count_sessions_branch_id'), table_name='stock_count_sessions')
    op.drop_table('stock_count_sessions')
    op.drop_index(op.f('ix_cashier_shifts_user_id'), table_name='cashier_shifts')
    op.drop_index('ix_cashier_shifts_user_branch_open_unique', table_name='cashier_shifts', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_cashier_shifts_location_id'), table_name='cashier_shifts')
    op.drop_index(op.f('ix_cashier_shifts_company_id'), table_name='cashier_shifts')
    op.drop_index(op.f('ix_cashier_shifts_branch_id'), table_name='cashier_shifts')
    op.drop_table('cashier_shifts')
    op.drop_index(op.f('ix_brands_company_id'), table_name='brands')
    op.drop_index('ix_brands_company_active', table_name='brands')
    op.drop_index(op.f('ix_brands_central_ready_location_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_central_location_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_central_branch_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_business_type'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_stock_locations_company_id'), table_name='stock_locations')
    op.drop_index(op.f('ix_stock_locations_branch_id'), table_name='stock_locations')
    op.drop_table('stock_locations')
    op.drop_index(op.f('ix_branch_settings_company_id'), table_name='branch_settings')
    op.drop_table('branch_settings')
    op.drop_index('ix_users_company_id_email_unique', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_units_company_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_price_lists_company_id'), table_name='price_lists')
    op.drop_table('price_lists')
    op.drop_index(op.f('ix_categories_company_id'), table_name='categories')
    op.drop_index('ix_categories_company_code_not_null_unique', table_name='categories', postgresql_where=sa.text('code IS NOT NULL'))
    op.drop_table('categories')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_operational_outbox_events_status'), table_name='operational_outbox_events')
    op.drop_index(op.f('ix_operational_outbox_events_event_type'), table_name='operational_outbox_events')
    op.drop_index(op.f('ix_operational_outbox_events_created_at'), table_name='operational_outbox_events')
    op.drop_index(op.f('ix_operational_outbox_events_company_id'), table_name='operational_outbox_events')
    op.drop_index(op.f('ix_operational_outbox_events_brand_id'), table_name='operational_outbox_events')
    op.drop_index(op.f('ix_operational_outbox_events_branch_id'), table_name='operational_outbox_events')
    op.drop_index(op.f('ix_operational_outbox_events_aggregate_id'), table_name='operational_outbox_events')
    op.drop_table('operational_outbox_events')
    op.drop_index(op.f('ix_companies_business_slug'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_branch_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_approval_grant_usages_company_branch_consumed', table_name='approval_grant_usages')
    op.drop_table('approval_grant_usages')
    # ### end Alembic commands ###
