#!/bin/sh
set -eu

ENV_FILE="${1:-.env.production}"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.prod.yml}"
BACKUP_ROOT="${PRODUCTION_BACKUP_ROOT:-backups}"
STATUS_TRIES="${PRODUCTION_STATUS_TRIES:-30}"
STATUS_SLEEP_SECONDS="${PRODUCTION_STATUS_SLEEP_SECONDS:-5}"
PRODUCTION_IMAGE_MODE="${PRODUCTION_IMAGE_MODE:-build}"
if [ "$PRODUCTION_IMAGE_MODE" = "pull" ]; then
  RELEASE_VERSION="${RELEASE_VERSION:-}"
else
  RELEASE_VERSION="${RELEASE_VERSION:-prod-$(date -u +%Y%m%dT%H%M%SZ)}"
fi
CREATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
RELEASE_DIR="releases/$RELEASE_VERSION"
BACKUP_LOG=""
BACKUP_PATH=""

fail() {
  printf 'ERROR: %s\n' "$1" >&2
  exit 1
}

require_executable() {
  script="$1"
  if [ ! -x "$script" ]; then
    fail "$script is missing or not executable"
  fi
}

validate_release_version() {
  if ! printf '%s' "$RELEASE_VERSION" | grep -Eq '^[A-Za-z0-9._-]+$'; then
    fail "RELEASE_VERSION may contain only letters, numbers, dot, underscore, and hyphen"
  fi
}

normalize_registry() {
  printf '%s' "${IMAGE_REGISTRY%/}"
}

normalize_namespace() {
  namespace="$1"
  namespace="${namespace#/}"
  printf '%s' "${namespace%/}"
}

configure_images() {
  case "$PRODUCTION_IMAGE_MODE" in
    build)
      BACKEND_IMAGE="${BACKEND_IMAGE:-restaurant-pos-backend:$RELEASE_VERSION}"
      FRONTEND_IMAGE="${FRONTEND_IMAGE:-restaurant-pos-frontend:$RELEASE_VERSION}"
      NGINX_IMAGE="${NGINX_IMAGE:-restaurant-pos-nginx:$RELEASE_VERSION}"
      ;;
    pull)
      if [ -z "${IMAGE_REGISTRY:-}" ]; then
        fail "IMAGE_REGISTRY is required when PRODUCTION_IMAGE_MODE=pull"
      fi
      if [ -z "${IMAGE_NAMESPACE:-}" ]; then
        fail "IMAGE_NAMESPACE is required when PRODUCTION_IMAGE_MODE=pull"
      fi
      registry="$(normalize_registry)"
      namespace="$(normalize_namespace "$IMAGE_NAMESPACE")"
      BACKEND_IMAGE="${BACKEND_IMAGE:-$registry/$namespace/restaurant-pos-backend:$RELEASE_VERSION}"
      FRONTEND_IMAGE="${FRONTEND_IMAGE:-$registry/$namespace/restaurant-pos-frontend:$RELEASE_VERSION}"
      NGINX_IMAGE="${NGINX_IMAGE:-$registry/$namespace/restaurant-pos-nginx:$RELEASE_VERSION}"
      ;;
    *)
      fail "PRODUCTION_IMAGE_MODE must be build or pull"
      ;;
  esac

  export BACKEND_IMAGE FRONTEND_IMAGE NGINX_IMAGE PRODUCTION_IMAGE_MODE
}

write_manifest() {
  verification_summary="$1"
  mkdir -p "$RELEASE_DIR"
  cat > "$RELEASE_DIR/release-manifest.txt" <<EOF
release_version=$RELEASE_VERSION
created_at_utc=$CREATED_AT
compose_project_name=${COMPOSE_PROJECT_NAME:-restaurant-pos-prod}
compose_file=$COMPOSE_FILE
image_mode=$PRODUCTION_IMAGE_MODE
backend_image=$BACKEND_IMAGE
frontend_image=$FRONTEND_IMAGE
nginx_image=$NGINX_IMAGE
backup_path=${BACKUP_PATH:-unknown}
deploy_verification=$verification_summary
notes=Generated by scripts/deploy-production.sh. Does not include secrets or full environment values.
EOF
}

printf 'Starting production deploy with env file: %s\n' "$ENV_FILE"
validate_release_version
configure_images
printf 'Using release version: %s\n' "$RELEASE_VERSION"
printf 'Using image mode: %s\n' "$PRODUCTION_IMAGE_MODE"

require_executable scripts/check-production-env.sh
require_executable scripts/backup-production.sh
require_executable scripts/run-production-migrations.sh
require_executable scripts/check-production-status.sh
require_executable scripts/smoke-production.sh

printf 'Validating production environment.\n'
scripts/check-production-env.sh "$ENV_FILE"

export PRODUCTION_ENV_FILE="$ENV_FILE"
export RELEASE_VERSION
export BACKEND_IMAGE FRONTEND_IMAGE NGINX_IMAGE

printf 'Validating production compose configuration: %s\n' "$COMPOSE_FILE"
docker compose -f "$COMPOSE_FILE" config >/dev/null

if [ "$PRODUCTION_IMAGE_MODE" = "pull" ]; then
  printf 'Pulling production images from registry.\n'
  docker compose -f "$COMPOSE_FILE" pull backend frontend nginx
fi

printf 'Creating pre-deploy backup.\n'
BACKUP_LOG="$(mktemp "${TMPDIR:-/tmp}/restaurant-pos-deploy-backup.XXXXXX")"
scripts/backup-production.sh "$BACKUP_ROOT" > "$BACKUP_LOG"
cat "$BACKUP_LOG"
BACKUP_PATH="$(sed -n 's/^Production backup completed: //p' "$BACKUP_LOG" | tail -n 1)"
rm -f "$BACKUP_LOG"

if [ "$PRODUCTION_IMAGE_MODE" = "build" ]; then
  printf 'Building production images.\n'
  docker compose -f "$COMPOSE_FILE" build
fi

printf 'Running production migrations.\n'
scripts/run-production-migrations.sh "$ENV_FILE"

printf 'Starting production application stack.\n'
if [ "$PRODUCTION_IMAGE_MODE" = "pull" ]; then
  docker compose -f "$COMPOSE_FILE" up -d --no-build
else
  docker compose -f "$COMPOSE_FILE" up -d
fi

printf 'Waiting for production readiness.\n'
try=1
while [ "$try" -le "$STATUS_TRIES" ]; do
  if scripts/check-production-status.sh; then
    printf '\nRunning production smoke test.\n'
    scripts/smoke-production.sh "$ENV_FILE"
    write_manifest "status_passed_smoke_passed"
    printf '\nProduction deploy completed successfully.\n'
    printf 'Release manifest: %s/release-manifest.txt\n' "$RELEASE_DIR"
    exit 0
  fi

  if [ "$try" -eq "$STATUS_TRIES" ]; then
    break
  fi

  printf 'Status check failed; retrying in %s seconds (%s/%s).\n' "$STATUS_SLEEP_SECONDS" "$try" "$STATUS_TRIES"
  sleep "$STATUS_SLEEP_SECONDS"
  try=$((try + 1))
done

fail "production deploy did not become ready after $STATUS_TRIES status check attempt(s)"
