"""create takeaway operational schema

Revision ID: p6takeaway0002
Revises: p6takeaway0001
Create Date: 2026-09-11 14:14:20.021835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'p6takeaway0002'
down_revision: Union[str, None] = 'p6takeaway0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('takeaway_branch_catalog_items',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('catalog_item_id', sa.UUID(), nullable=False),
    sa.Column('price_override', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_branch_catalog_items')),
    sa.UniqueConstraint('branch_id', 'catalog_item_id', name='uq_takeaway_branch_catalog_item')
    )
    op.create_index('ix_takeaway_branch_catalog_scope', 'takeaway_branch_catalog_items', ['company_id', 'brand_id', 'branch_id'], unique=False)
    op.create_table('takeaway_catalog_items',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('unit', sa.String(length=40), server_default=sa.text("'ชิ้น'"), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('kitchen_station', sa.String(length=80), nullable=True),
    sa.Column('track_stock', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_takeaway_catalog_items_ck_takeaway_catalog_item_price')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_catalog_items')),
    sa.UniqueConstraint('company_id', 'brand_id', 'sku', name='uq_takeaway_catalog_item_sku')
    )
    op.create_index(op.f('ix_takeaway_catalog_items_barcode'), 'takeaway_catalog_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_takeaway_catalog_items_category_id'), 'takeaway_catalog_items', ['category_id'], unique=False)
    op.create_index('ix_takeaway_catalog_items_scope', 'takeaway_catalog_items', ['company_id', 'brand_id', 'is_active'], unique=False)
    op.create_table('takeaway_categories',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_categories')),
    sa.UniqueConstraint('company_id', 'brand_id', 'code', name='uq_takeaway_category_code')
    )
    op.create_index('ix_takeaway_categories_scope', 'takeaway_categories', ['company_id', 'brand_id', 'is_active'], unique=False)
    op.create_table('takeaway_central_order_items',
    sa.Column('central_order_id', sa.UUID(), nullable=False),
    sa.Column('catalog_item_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('item_name', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('source_kind', sa.String(length=20), server_default=sa.text("'catalog'"), nullable=False),
    sa.Column('approval_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_takeaway_central_order_items_ck_takeaway_central_item_quantity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_central_order_items'))
    )
    op.create_index(op.f('ix_takeaway_central_order_items_central_order_id'), 'takeaway_central_order_items', ['central_order_id'], unique=False)
    op.create_table('takeaway_central_order_rounds',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_central_order_rounds')),
    sa.UniqueConstraint('brand_id', 'business_date', 'round_no', name='uq_takeaway_central_round')
    )
    op.create_table('takeaway_central_orders',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=80), nullable=False),
    sa.Column('order_type', sa.String(length=20), server_default=sa.text("'regular'"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'submitted'"), nullable=False),
    sa.Column('requested_delivery_date', sa.Date(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_central_orders')),
    sa.UniqueConstraint('branch_id', 'order_number', name='uq_takeaway_central_order_number')
    )
    op.create_index('ix_takeaway_central_orders_status', 'takeaway_central_orders', ['company_id', 'brand_id', 'status'], unique=False)
    op.create_table('takeaway_credit_accounts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credit_limit >= 0', name=op.f('ck_takeaway_credit_accounts_ck_takeaway_credit_limit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_credit_accounts')),
    sa.UniqueConstraint('company_id', 'brand_id', 'branch_id', name='uq_takeaway_credit_account')
    )
    op.create_table('takeaway_credit_entries',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_credit_entries')),
    sa.UniqueConstraint('idempotency_key', name='uq_takeaway_credit_entry_idempotency')
    )
    op.create_index(op.f('ix_takeaway_credit_entries_account_id'), 'takeaway_credit_entries', ['account_id'], unique=False)
    op.create_table('takeaway_import_batches',
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('source_snapshot', sa.String(length=100), nullable=False),
    sa.Column('manifest_digest', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=20), server_default=sa.text("'dry_run'"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('total_records', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('accepted_records', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejected_records', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_import_batches')),
    sa.UniqueConstraint('manifest_digest', name='uq_takeaway_import_manifest_digest')
    )
    op.create_table('takeaway_import_records',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('source_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_import_records')),
    sa.UniqueConstraint('batch_id', 'source_type', 'source_id', name='uq_takeaway_import_record_source')
    )
    op.create_index(op.f('ix_takeaway_import_records_batch_id'), 'takeaway_import_records', ['batch_id'], unique=False)
    op.create_table('takeaway_kitchen_tickets',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('queue_number', sa.Integer(), nullable=False),
    sa.Column('station', sa.String(length=80), server_default=sa.text("'default'"), nullable=False),
    sa.Column('item_name', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_kitchen_tickets')),
    sa.UniqueConstraint('order_item_id', name='uq_takeaway_kitchen_order_item')
    )
    op.create_index('ix_takeaway_kitchen_queue', 'takeaway_kitchen_tickets', ['branch_id', 'station', 'status'], unique=False)
    op.create_table('takeaway_operational_outbox',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('contract_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_operational_outbox')),
    sa.UniqueConstraint('idempotency_key', name='uq_takeaway_outbox_idempotency')
    )
    op.create_index(op.f('ix_takeaway_operational_outbox_company_id'), 'takeaway_operational_outbox', ['company_id'], unique=False)
    op.create_index(op.f('ix_takeaway_operational_outbox_event_type'), 'takeaway_operational_outbox', ['event_type'], unique=False)
    op.create_table('takeaway_order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('catalog_item_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kitchen_station', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_takeaway_order_items_ck_takeaway_order_item_quantity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_order_items'))
    )
    op.create_index('ix_takeaway_order_items_order', 'takeaway_order_items', ['order_id'], unique=False)
    op.create_table('takeaway_orders',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=60), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('queue_number', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), server_default=sa.text("'counter'"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('fulfillment_status', sa.String(length=30), server_default=sa.text("'awaiting_payment'"), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('offline_device_id', sa.UUID(), nullable=True),
    sa.Column('offline_sequence', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('counter', 'qr', 'online', 'import')", name=op.f('ck_takeaway_orders_ck_takeaway_order_channel')),
    sa.CheckConstraint("fulfillment_status IN ('awaiting_payment', 'queued', 'preparing', 'ready', 'picked_up', 'cancelled')", name=op.f('ck_takeaway_orders_ck_takeaway_order_fulfillment_status')),
    sa.CheckConstraint("status IN ('draft', 'paid', 'cancelled', 'refunded')", name=op.f('ck_takeaway_orders_ck_takeaway_order_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_orders')),
    sa.UniqueConstraint('branch_id', 'idempotency_key', name='uq_takeaway_order_idempotency'),
    sa.UniqueConstraint('branch_id', 'order_number', name='uq_takeaway_order_number')
    )
    op.create_index('ix_takeaway_orders_queue', 'takeaway_orders', ['branch_id', 'business_date', 'queue_number'], unique=False)
    op.create_index('ix_takeaway_orders_scope_status', 'takeaway_orders', ['company_id', 'brand_id', 'branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_takeaway_orders_shift_id'), 'takeaway_orders', ['shift_id'], unique=False)
    op.create_table('takeaway_payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'captured'"), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_takeaway_payments_ck_takeaway_payment_amount')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_payments')),
    sa.UniqueConstraint('order_id', 'idempotency_key', name='uq_takeaway_payment_idempotency')
    )
    op.create_index(op.f('ix_takeaway_payments_order_id'), 'takeaway_payments', ['order_id'], unique=False)
    op.create_table('takeaway_pickup_tokens',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_pickup_tokens')),
    sa.UniqueConstraint('order_id', name=op.f('uq_takeaway_pickup_tokens_order_id')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_takeaway_pickup_tokens_token_hash'))
    )
    op.create_table('takeaway_production_batches',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'planned'"), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_production_batches')),
    sa.UniqueConstraint('company_id', 'batch_number', name='uq_takeaway_production_batch')
    )
    op.create_table('takeaway_production_lines',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('planned_qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('planned_qty > 0', name=op.f('ck_takeaway_production_lines_ck_takeaway_production_line_qty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_production_lines'))
    )
    op.create_index(op.f('ix_takeaway_production_lines_batch_id'), 'takeaway_production_lines', ['batch_id'], unique=False)
    op.create_table('takeaway_receipts',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_receipts')),
    sa.UniqueConstraint('order_id', name=op.f('uq_takeaway_receipts_order_id')),
    sa.UniqueConstraint('receipt_number', name='uq_takeaway_receipt_number')
    )
    op.create_table('takeaway_reference_projections',
    sa.Column('aggregate_type', sa.String(length=40), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_digest', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("aggregate_type IN ('company', 'brand', 'branch', 'brand_branch', 'user')", name=op.f('ck_takeaway_reference_projections_ck_takeaway_reference_projection_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_reference_projections')),
    sa.UniqueConstraint('aggregate_type', 'aggregate_id', name='uq_takeaway_reference_projection_aggregate')
    )
    op.create_index(op.f('ix_takeaway_reference_projections_company_id'), 'takeaway_reference_projections', ['company_id'], unique=False)
    op.create_table('takeaway_shifts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('counted_cash', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('close_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed')", name=op.f('ck_takeaway_shifts_ck_takeaway_shift_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_shifts')),
    sa.UniqueConstraint('branch_id', 'business_date', 'round_no', name='uq_takeaway_shift_round')
    )
    op.create_index('ix_takeaway_shifts_scope_status', 'takeaway_shifts', ['company_id', 'brand_id', 'branch_id', 'status'], unique=False)
    op.create_table('takeaway_stock_balances',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('lot_code', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('on_hand_qty', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('reserved_qty', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('on_hand_qty >= 0', name=op.f('ck_takeaway_stock_balances_ck_takeaway_stock_on_hand')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_stock_balances')),
    sa.UniqueConstraint('company_id', 'location_id', 'item_id', 'lot_code', name='uq_takeaway_stock_balance')
    )
    op.create_table('takeaway_stock_movements',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('lot_code', sa.String(length=100), server_default=sa.text("''"), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('production_batch_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('transfer_id', sa.UUID(), nullable=True),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity_delta <> 0', name=op.f('ck_takeaway_stock_movements_ck_takeaway_stock_movement_nonzero')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_stock_movements')),
    sa.UniqueConstraint('idempotency_key', name='uq_takeaway_stock_movement_idempotency')
    )
    op.create_index('ix_takeaway_stock_movements_item', 'takeaway_stock_movements', ['company_id', 'location_id', 'item_id', 'occurred_at'], unique=False)
    op.create_table('takeaway_transfer_items',
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('requested_qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('shipped_qty', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('received_qty', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requested_qty > 0', name=op.f('ck_takeaway_transfer_items_ck_takeaway_transfer_item_qty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_transfer_items'))
    )
    op.create_index(op.f('ix_takeaway_transfer_items_transfer_id'), 'takeaway_transfer_items', ['transfer_id'], unique=False)
    op.create_table('takeaway_transfers',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('transfer_number', sa.String(length=80), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=False),
    sa.Column('to_location_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_transfers')),
    sa.UniqueConstraint('company_id', 'transfer_number', name='uq_takeaway_transfer_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('takeaway_transfers')
    op.drop_index(op.f('ix_takeaway_transfer_items_transfer_id'), table_name='takeaway_transfer_items')
    op.drop_table('takeaway_transfer_items')
    op.drop_index('ix_takeaway_stock_movements_item', table_name='takeaway_stock_movements')
    op.drop_table('takeaway_stock_movements')
    op.drop_table('takeaway_stock_balances')
    op.drop_index('ix_takeaway_shifts_scope_status', table_name='takeaway_shifts')
    op.drop_table('takeaway_shifts')
    op.drop_index(op.f('ix_takeaway_reference_projections_company_id'), table_name='takeaway_reference_projections')
    op.drop_table('takeaway_reference_projections')
    op.drop_table('takeaway_receipts')
    op.drop_index(op.f('ix_takeaway_production_lines_batch_id'), table_name='takeaway_production_lines')
    op.drop_table('takeaway_production_lines')
    op.drop_table('takeaway_production_batches')
    op.drop_table('takeaway_pickup_tokens')
    op.drop_index(op.f('ix_takeaway_payments_order_id'), table_name='takeaway_payments')
    op.drop_table('takeaway_payments')
    op.drop_index(op.f('ix_takeaway_orders_shift_id'), table_name='takeaway_orders')
    op.drop_index('ix_takeaway_orders_scope_status', table_name='takeaway_orders')
    op.drop_index('ix_takeaway_orders_queue', table_name='takeaway_orders')
    op.drop_table('takeaway_orders')
    op.drop_index('ix_takeaway_order_items_order', table_name='takeaway_order_items')
    op.drop_table('takeaway_order_items')
    op.drop_index(op.f('ix_takeaway_operational_outbox_event_type'), table_name='takeaway_operational_outbox')
    op.drop_index(op.f('ix_takeaway_operational_outbox_company_id'), table_name='takeaway_operational_outbox')
    op.drop_table('takeaway_operational_outbox')
    op.drop_index('ix_takeaway_kitchen_queue', table_name='takeaway_kitchen_tickets')
    op.drop_table('takeaway_kitchen_tickets')
    op.drop_index(op.f('ix_takeaway_import_records_batch_id'), table_name='takeaway_import_records')
    op.drop_table('takeaway_import_records')
    op.drop_table('takeaway_import_batches')
    op.drop_index(op.f('ix_takeaway_credit_entries_account_id'), table_name='takeaway_credit_entries')
    op.drop_table('takeaway_credit_entries')
    op.drop_table('takeaway_credit_accounts')
    op.drop_index('ix_takeaway_central_orders_status', table_name='takeaway_central_orders')
    op.drop_table('takeaway_central_orders')
    op.drop_table('takeaway_central_order_rounds')
    op.drop_index(op.f('ix_takeaway_central_order_items_central_order_id'), table_name='takeaway_central_order_items')
    op.drop_table('takeaway_central_order_items')
    op.drop_index('ix_takeaway_categories_scope', table_name='takeaway_categories')
    op.drop_table('takeaway_categories')
    op.drop_index('ix_takeaway_catalog_items_scope', table_name='takeaway_catalog_items')
    op.drop_index(op.f('ix_takeaway_catalog_items_category_id'), table_name='takeaway_catalog_items')
    op.drop_index(op.f('ix_takeaway_catalog_items_barcode'), table_name='takeaway_catalog_items')
    op.drop_table('takeaway_catalog_items')
    op.drop_index('ix_takeaway_branch_catalog_scope', table_name='takeaway_branch_catalog_items')
    op.drop_table('takeaway_branch_catalog_items')
    # ### end Alembic commands ###
