"""add takeaway migration masters and archive

Revision ID: p6takeaway0003
Revises: p6takeaway0002
Create Date: 2026-09-11 14:43:13.455695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'p6takeaway0003'
down_revision: Union[str, None] = 'p6takeaway0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('takeaway_historical_archive',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.String(length=160), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('document_number', sa.String(length=160), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_historical_archive')),
    sa.UniqueConstraint('import_batch_id', 'record_type', 'source_id', name='uq_takeaway_history_source')
    )
    op.create_index('ix_takeaway_history_scope', 'takeaway_historical_archive', ['company_id', 'brand_id', 'record_type'], unique=False)
    op.create_table('takeaway_recipe_ingredients',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_takeaway_recipe_ingredients_ck_takeaway_recipe_ingredient_qty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_recipe_ingredients')),
    sa.UniqueConstraint('recipe_id', 'item_id', name='uq_takeaway_recipe_ingredient')
    )
    op.create_index(op.f('ix_takeaway_recipe_ingredients_recipe_id'), 'takeaway_recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('takeaway_recipes',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('output_item_id', sa.UUID(), nullable=False),
    sa.Column('recipe_type', sa.String(length=30), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('yield_qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('yield_unit', sa.String(length=40), nullable=False),
    sa.Column('loss_percent', sa.Numeric(precision=7, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('yield_qty > 0', name=op.f('ck_takeaway_recipes_ck_takeaway_recipe_yield')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_recipes')),
    sa.UniqueConstraint('company_id', 'brand_id', 'output_item_id', 'branch_id', 'version_no', name='uq_takeaway_recipe_version')
    )
    op.create_table('takeaway_replenishment_policies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('safety_stock_percent', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('safety_stock_qty', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('pack_size', sa.Numeric(precision=15, scale=4), server_default=sa.text('1'), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('forecast_method', sa.String(length=40), server_default=sa.text("'auto'"), nullable=False),
    sa.Column('minimum_order_qty', sa.Numeric(precision=15, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pack_size > 0', name=op.f('ck_takeaway_replenishment_policies_ck_takeaway_replenishment_pack_size')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_replenishment_policies')),
    sa.UniqueConstraint('brand_id', 'branch_id', 'item_id', name='uq_takeaway_replenishment_policy')
    )
    op.create_table('takeaway_stock_locations',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("location_type IN ('central_raw', 'central_ready', 'store', 'transit', 'waste')", name=op.f('ck_takeaway_stock_locations_ck_takeaway_stock_location_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_stock_locations')),
    sa.UniqueConstraint('company_id', 'code', name='uq_takeaway_stock_location_code')
    )
    op.create_table('takeaway_units',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('decimal_places', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('decimal_places BETWEEN 0 AND 6', name=op.f('ck_takeaway_units_ck_takeaway_unit_decimal_places')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_takeaway_units')),
    sa.UniqueConstraint('company_id', 'code', name='uq_takeaway_unit_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('takeaway_units')
    op.drop_table('takeaway_stock_locations')
    op.drop_table('takeaway_replenishment_policies')
    op.drop_table('takeaway_recipes')
    op.drop_index(op.f('ix_takeaway_recipe_ingredients_recipe_id'), table_name='takeaway_recipe_ingredients')
    op.drop_table('takeaway_recipe_ingredients')
    op.drop_index('ix_takeaway_history_scope', table_name='takeaway_historical_archive')
    op.drop_table('takeaway_historical_archive')
    # ### end Alembic commands ###
